server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-authuser 
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql:true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.himax.ead: DEBUG
