version: "3.9"

services:
  ead-authuser:
    image: postgres:16.0-alpine3.18
    container_name: ead-authuser
    environment:
      POSTGRES_DB: ead-authuser
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5433:5432"
    networks:
      - ead-network

  ead-notification:
    image: postgres:16.0-alpine3.18
    container_name: ead-notification
    environment:
      POSTGRES_DB: ead-notification
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5434:5432"
    networks:
      - ead-network

  ead-course:
    image: postgres:16.0-alpine3.18
    container_name: ead-course
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5435:5432"
    networks:
      - ead-network

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ead-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: filebeat
    user: root
    volumes:
      - ./logs:/usr/share/filebeat/logs:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - registry:/usr/share/filebeat/data:rw
    command: >
      filebeat -e --strict.perms=false
      -E output.elasticsearch.hosts=["localhost:9200"]
    networks:
      - elastic

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 1GB
    environment:
      - discovery.type=single-node

  kib01:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kib01
    ports:
      - "5601:5601"

volumes:
  registry:

networks:
  ead-network:
    driver: bridge
  elastic:
    driver: bridge