version: "3.9"

services:
  ead-authuser:
    image: postgres:16.0-alpine3.18
    container_name: ead-authuser
    environment:
      POSTGRES_DB: ead-authuser
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5433:5432"
    networks:
      - ead-network

  ead-notification:
    image: postgres:16.0-alpine3.18
    container_name: ead-notification
    environment:
      POSTGRES_DB: ead-notification
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5434:5432"
    networks:
      - ead-network

  ead-course:
    image: postgres:16.0-alpine3.18
    container_name: ead-course
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: administrator
    ports:
      - "5435:5432"
    networks:
      - ead-network

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ead-network

networks:
  ead-network:
    driver: bridge
