spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'


  # Necessary because the registration name is not default, just 'configserver'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: admin
      password: admin
  # ****************************************************************************
