server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE
          predicates:
            - Path=/ead-course/**
  output:
    ansi:
      enabled: ALWAYS
      
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost