server:
  port: 8761

spring:
  application:
    name: ead-service-registry
  output:
    ansi:
      enabled: ALWAYS

ead:
  serviceRegistry:
    username: admin
    password: admin

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka"
